// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QN-kaVKTzzhVjGcD1rX4YmwoQsm7x8s',
    appId: '1:579400949348:web:1577b607ded530d7d20971',
    messagingSenderId: '579400949348',
    projectId: 'bluebubbles-f0b2',
    authDomain: 'bluebubbles-f0b2.firebaseapp.com',
    storageBucket: 'bluebubbles-f0b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO8JbePbggoxGI8ZGSLORCOnaRGESngiU',
    appId: '1:579400949348:android:09c42f8d0e41fd40d20971',
    messagingSenderId: '579400949348',
    projectId: 'bluebubbles-f0b2',
    storageBucket: 'bluebubbles-f0b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxg56Shmwy5Wnk28HxzGH4qNOMHpmm1ck',
    appId: '1:579400949348:ios:62f0da365d3012efd20971',
    messagingSenderId: '579400949348',
    projectId: 'bluebubbles-f0b2',
    storageBucket: 'bluebubbles-f0b2.firebasestorage.app',
    iosBundleId: 'com.example.insclon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxg56Shmwy5Wnk28HxzGH4qNOMHpmm1ck',
    appId: '1:579400949348:ios:62f0da365d3012efd20971',
    messagingSenderId: '579400949348',
    projectId: 'bluebubbles-f0b2',
    storageBucket: 'bluebubbles-f0b2.firebasestorage.app',
    iosBundleId: 'com.example.insclon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6QN-kaVKTzzhVjGcD1rX4YmwoQsm7x8s',
    appId: '1:579400949348:web:b5ac2ad3718b19f2d20971',
    messagingSenderId: '579400949348',
    projectId: 'bluebubbles-f0b2',
    authDomain: 'bluebubbles-f0b2.firebaseapp.com',
    storageBucket: 'bluebubbles-f0b2.firebasestorage.app',
  );
}
